### ISSUE TITLE
Will not compile with Cocoapods when using frameworks

### ISSUE THREAD

**Issue by mergesort** [wordpress-mobile/EmailChecker#1]
iOS 8 introduced static frameworks, which now are supported by Cocoapods. EmailChecker fails to compile when using frameworks, with an error of 

```
Could not build module 'EmailChecker'
```

The error is actually happening on `#include "string"`, on line 4 of `EmailDomainSpellChecker.h`.

I don't really have much more useful info because I'm familiar enough with C++, but love the library and would love to be able to integrate it again.

**Comment by maxme** [comment]
> `#include "string"`

Looks like it can't find the STL headers. Can you send a sample project with the issue you're experiencing?

**Comment by mergesort** [comment]
Here you go. It's just a blank project with the pod imported.

http://www.filedropper.com/email-test

**Comment by mergesort** [comment]
@maxme Looks like this isn't your bug, but Apple's. Do you know of any way to work around it? Kinda hard to expect a yes, since it's in the STL string class.

http://openradar.appspot.com/20503249
